version: '2.4'

services:
  pia-next-gen-vpn:
    container_name: pia-next-gen-vpn
    image: ghcr.io/ivanjosipovic/pia-next-gen-vpn/pia-next-gen-vpn:latest
    build:
      context: .
      dockerfile: Dockerfile
    sysctls:
    - net.ipv6.conf.all.disable_ipv6=1
    - net.ipv6.conf.default.disable_ipv6=1
    environment:
      - PIA_AUTOCONNECT=openvpn_udp_standard
      - PIA_USER=
      - PIA_PASS=
      - PIA_DNS=true
      - PIA_PF=true
      - MAX_LATENCY=0.05
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - "/dev/net/tun:/dev/net/tun"
    restart: always